INSERT INTO lib_publishings (id, name) VALUES (1, 'Mitti Yulduz');
INSERT INTO lib_publishings (id, name) VALUES (2, 'O`zbekiston nashriyoti');
INSERT INTO lib_publishings (id, name) VALUES (3, 'Ta`lim nashriyoti');
INSERT INTO lib_publishings (id, name) VALUES (4, 'Sharq');
INSERT INTO lib_publishings (id, name) VALUES (5, 'Toshkent');
INSERT INTO lib_publishings (id, name) VALUES (6, 'Durdona');
INSERT INTO lib_publishings (id, name) VALUES (7, 'Buxoro');
INSERT INTO lib_publishings (id, name) VALUES (8, 'Fan');
INSERT INTO lib_publishings (id, name) VALUES (9, 'Go to print');
INSERT INTO lib_publishings (id, name) VALUES (10, 'Innovatsiya-Ziyo');
INSERT INTO lib_publishings (id, name) VALUES (11, 'Donishmand Ziyosi');
INSERT INTO lib_publishings (id, name) VALUES (12, 'O''zbekiston xalqaro akademiyasi');
INSERT INTO lib_publishings (id, name) VALUES (13, 'Paradigma');
INSERT INTO lib_publishings (id, name) VALUES (14, 'Nif Msh');
INSERT INTO lib_publishings (id, name) VALUES (15, 'Yoshlar nashriyoti uyi');
INSERT INTO lib_publishings (id, name) VALUES (16, 'Asian Book House');
INSERT INTO lib_publishings (id, name) VALUES (17, 'Tafakkur avlodi');
INSERT INTO lib_publishings (id, name) VALUES (18, 'Excellent Polygraphy');
INSERT INTO lib_publishings (id, name) VALUES (19, 'Kamalak');
INSERT INTO lib_publishings (id, name) VALUES (20, 'O`qituvchi');
INSERT INTO lib_publishings (id, name) VALUES (21, 'Ziyo nashr');
INSERT INTO lib_publishings (id, name) VALUES (22, 'Gafur Gulom');
INSERT INTO lib_publishings (id, name) VALUES (23, 'Ozbekiston milliy ensiklopediyasi');
INSERT INTO lib_publishings (id, name) VALUES (24, 'Fan va texnologiya');
INSERT INTO lib_publishings (id, name) VALUES (25, 'Yangi asr avlodi');
INSERT INTO lib_publishings (id, name) VALUES (26, 'Ijod press');
INSERT INTO lib_publishings (id, name) VALUES (27, 'Turon Zamin ziyo');
INSERT INTO lib_publishings (id, name) VALUES (28, 'Iqtisod-Moliya');
INSERT INTO lib_publishings (id, name) VALUES (29, 'Voris');
INSERT INTO lib_publishings (id, name) VALUES (30, 'Noshir');
INSERT INTO lib_publishings (id, name) VALUES (31, 'O''zbekiston faylasuflar milliy jamiyati');
INSERT INTO lib_publishings (id, name) VALUES (32, 'Sano-Standart');
INSERT INTO lib_publishings (id, name) VALUES (33, 'Muharrir');
INSERT INTO lib_publishings (id, name) VALUES (34, 'Dizayn-press');
INSERT INTO lib_publishings (id, name) VALUES (35, 'Visshaya shkola');
INSERT INTO lib_publishings (id, name) VALUES (36, 'Nishon noshir');
INSERT INTO lib_publishings (id, name) VALUES (37, 'Manaviyat');
INSERT INTO lib_publishings (id, name) VALUES (38, 'Innovatsion rivojlanish matbaa uyi');
INSERT INTO lib_publishings (id, name) VALUES (39, 'Shafoat Nur Fayz');
INSERT INTO lib_publishings (id, name) VALUES (40, 'Tamaddun');
INSERT INTO lib_publishings (id, name) VALUES (41, 'Mejdunarodnoy islamskoy akademii Uzbekistana');
INSERT INTO lib_publishings (id, name) VALUES (42, 'Spectrum Media Group');
INSERT INTO lib_publishings (id, name) VALUES (43, 'Barkamol fayz media');
INSERT INTO lib_publishings (id, name) VALUES (44, 'Ilm-Ziyo');
INSERT INTO lib_publishings (id, name) VALUES (45, 'Yangi kitob');
INSERT INTO lib_publishings (id, name) VALUES (46, 'Vneshinvestprom');
INSERT INTO lib_publishings (id, name) VALUES (47, 'Moskva');
INSERT INTO lib_publishings (id, name) VALUES (48, 'Davr-press');
INSERT INTO lib_publishings (id, name) VALUES (49, 'Kamalak-press');
INSERT INTO lib_publishings (id, name) VALUES (50, 'Sovetskiy pisatel');
INSERT INTO lib_publishings (id, name) VALUES (51, 'Mumtoz soz');
INSERT INTO lib_publishings (id, name) VALUES (52, 'Cle International');
INSERT INTO lib_publishings (id, name) VALUES (53, 'Biznes-Katalog');
INSERT INTO lib_publishings (id, name) VALUES (54, 'Hueber Verlog');
INSERT INTO lib_publishings (id, name) VALUES (55, 'Talqin');
INSERT INTO lib_publishings (id, name) VALUES (56, 'Musiqa');
INSERT INTO lib_publishings (id, name) VALUES (57, 'Art Flex');
INSERT INTO lib_publishings (id, name) VALUES (58, 'Akademnashr');
INSERT INTO lib_publishings (id, name) VALUES (59, 'Navoiy universiteti');
INSERT INTO lib_publishings (id, name) VALUES (60, 'Alisher Navoiy nomidagi milliy kutubxona');
INSERT INTO lib_publishings (id, name) VALUES (61, 'Muxr-press');
INSERT INTO lib_publishings (id, name) VALUES (62, 'Cho`lpon');
INSERT INTO lib_publishings (id, name) VALUES (63, 'SMI-Asia');
INSERT INTO lib_publishings (id, name) VALUES (64, 'Buxoro viloyat bosmaxonasi');
INSERT INTO lib_publishings (id, name) VALUES (65, 'Toshkent islom universiteti');
INSERT INTO lib_publishings (id, name) VALUES (66, 'Navruz');
INSERT INTO lib_publishings (id, name) VALUES (67, 'Movarounnahr');
INSERT INTO lib_publishings (id, name) VALUES (68, 'Adolat');
INSERT INTO lib_publishings (id, name) VALUES (69, 'Yangi nashr');
INSERT INTO lib_publishings (id, name) VALUES (70, 'Samarqand');
INSERT INTO lib_publishings (id, name) VALUES (71, 'Sankt-Peterburg');
INSERT INTO lib_publishings (id, name) VALUES (72, 'O`zbekiston');
INSERT INTO lib_publishings (id, name) VALUES (73, 'O''zRFA ishlar qoshidagi kichik bosmaxona ');
INSERT INTO lib_publishings (id, name) VALUES (74, 'Xorazm');
INSERT INTO lib_publishings (id, name) VALUES (75, 'Adib');
INSERT INTO lib_publishings (id, name) VALUES (76, 'Fan va ta`lim poligraf');
INSERT INTO lib_publishings (id, name) VALUES (77, 'Geo fan poligraf');
INSERT INTO lib_publishings (id, name) VALUES (78, 'Istburn');
INSERT INTO lib_publishings (id, name) VALUES (79, 'Tokio');
INSERT INTO lib_publishings (id, name) VALUES (80, 'Prinston');
INSERT INTO lib_publishings (id, name) VALUES (81, 'Oksford');
INSERT INTO lib_publishings (id, name) VALUES (82, 'Annapolis');
INSERT INTO lib_publishings (id, name) VALUES (83, 'London');
INSERT INTO lib_publishings (id, name) VALUES (84, 'Stendford');
INSERT INTO lib_publishings (id, name) VALUES (85, 'Los-Anjeles');
INSERT INTO lib_publishings (id, name) VALUES (86, 'Washington');
INSERT INTO lib_publishings (id, name) VALUES (87, 'New-York');
INSERT INTO lib_publishings (id, name) VALUES (88, 'Kembridj');
INSERT INTO lib_publishings (id, name) VALUES (89, 'Gonoluli');
INSERT INTO lib_publishings (id, name) VALUES (90, 'Berkleu');
INSERT INTO lib_publishings (id, name) VALUES (91, 'Ann-arbor');
INSERT INTO lib_publishings (id, name) VALUES (92, 'Folkston');
INSERT INTO lib_publishings (id, name) VALUES (93, 'Boston');
INSERT INTO lib_publishings (id, name) VALUES (94, 'Uzgidrameta');
INSERT INTO lib_publishings (id, name) VALUES (95, 'OTIS Toshkent');
INSERT INTO lib_publishings (id, name) VALUES (96, 'Riso-Toshkent');
INSERT INTO lib_publishings (id, name) VALUES (97, 'Abu-matbuot Konsalting');
INSERT INTO lib_publishings (id, name) VALUES (98, 'Algo-Boss');
INSERT INTO lib_publishings (id, name) VALUES (99, 'Ilmiy qo''llanma');
INSERT INTO lib_publishings (id, name) VALUES (100, 'G.Gulyama');
INSERT INTO lib_publishings (id, name) VALUES (101, 'Lider-press');
INSERT INTO lib_publishings (id, name) VALUES (102, 'Mehnat');
INSERT INTO lib_publishings (id, name) VALUES (103, 'Namangan');
INSERT INTO lib_publishings (id, name) VALUES (104, 'Matbaa ijodiy uyi');
INSERT INTO lib_publishings (id, name) VALUES (105, 'Uzbekiston milliy universiteti (UzMU)');
INSERT INTO lib_publishings (id, name) VALUES (106, 'Olmos qilich');
INSERT INTO lib_publishings (id, name) VALUES (107, 'Baktriya - press');
INSERT INTO lib_publishings (id, name) VALUES (108, 'Islom universiteti');
INSERT INTO lib_publishings (id, name) VALUES (109, 'Termiz');
INSERT INTO lib_publishings (id, name) VALUES (110, 'Tafakkur');
INSERT INTO lib_publishings (id, name) VALUES (111, 'Tailand');
INSERT INTO lib_publishings (id, name) VALUES (112, 'Turon-Iqbol');
INSERT INTO lib_publishings (id, name) VALUES (113, 'Universitet');
INSERT INTO lib_publishings (id, name) VALUES (114, 'Chashma print');
INSERT INTO lib_publishings (id, name) VALUES (115, 'Nihol');
INSERT INTO lib_publishings (id, name) VALUES (116, 'Ma''ruza matni');
INSERT INTO lib_publishings (id, name) VALUES (117, 'Ma''lumotlar to''plami');
INSERT INTO lib_publishings (id, name) VALUES (118, 'Baqtriya -press');
INSERT INTO lib_publishings (id, name) VALUES (119, 'Tafakkur bostoni');
INSERT INTO lib_publishings (id, name) VALUES (120, 'Kolos');
INSERT INTO lib_publishings (id, name) VALUES (121, 'Dushanbe');
INSERT INTO lib_publishings (id, name) VALUES (122, 'Extremum-press');
INSERT INTO lib_publishings (id, name) VALUES (123, 'Barkamol fayz mediya');
INSERT INTO lib_publishings (id, name) VALUES (124, 'Sanat');
INSERT INTO lib_publishings (id, name) VALUES (125, 'Milliy universitet Toshkent');
INSERT INTO lib_publishings (id, name) VALUES (126, 'Bayoz Toshkent');
INSERT INTO lib_publishings (id, name) VALUES (127, 'Moliya');
INSERT INTO lib_publishings (id, name) VALUES (128, 'O''zbekiston Toshkent');
INSERT INTO lib_publishings (id, name) VALUES (129, '???°NS?»???? ???°N?N€??N‘N‚??');
INSERT INTO lib_publishings (id, name) VALUES (130, 'UNESCO');
INSERT INTO lib_publishings (id, name) VALUES (131, '??N€???°??N‡');
INSERT INTO lib_publishings (id, name) VALUES (132, 'Urganch');
INSERT INTO lib_publishings (id, name) VALUES (133, 'Andijon');
INSERT INTO lib_publishings (id, name) VALUES (134, 'Chirchiq');
INSERT INTO lib_publishings (id, name) VALUES (135, 'USA');
INSERT INTO lib_publishings (id, name) VALUES (136, '?”??????N?');
INSERT INTO lib_publishings (id, name) VALUES (137, 'Donish');
INSERT INTO lib_publishings (id, name) VALUES (138, 'Irfon');
INSERT INTO lib_publishings (id, name) VALUES (139, 'Wiley');
INSERT INTO lib_publishings (id, name) VALUES (140, '???·?±?µ????N?N‚????');
INSERT INTO lib_publishings (id, name) VALUES (141, '"Extremum press" ');
INSERT INTO lib_publishings (id, name) VALUES (142, 'Photopress ');
INSERT INTO lib_publishings (id, name) VALUES (143, 'Istambul');
INSERT INTO lib_publishings (id, name) VALUES (144, 'Berlin');
INSERT INTO lib_publishings (id, name) VALUES (145, 'O`zbekiston faylasuflar milliy jamiyati');
INSERT INTO lib_publishings (id, name) VALUES (146, 'Ankara');
INSERT INTO lib_publishings (id, name) VALUES (147, 'Istanbul');
INSERT INTO lib_publishings (id, name) VALUES (148, 'Ozbekiston milliy kutubxonasi');
INSERT INTO lib_publishings (id, name) VALUES (149, 'Lesson-press');
INSERT INTO lib_publishings (id, name) VALUES (150, 'Of set Print Nihol');
INSERT INTO lib_publishings (id, name) VALUES (151, 'Karshi');
INSERT INTO lib_publishings (id, name) VALUES (152, 'Nukus');
INSERT INTO lib_publishings (id, name) VALUES (153, 'Hueber Verlag');
INSERT INTO lib_publishings (id, name) VALUES (154, 'Hachette Livre');
INSERT INTO lib_publishings (id, name) VALUES (155, 'Auflage ');
INSERT INTO lib_publishings (id, name) VALUES (156, 'Paris');
INSERT INTO lib_publishings (id, name) VALUES (157, 'Adabiyot uchqunlari');
INSERT INTO lib_publishings (id, name) VALUES (158, 'Nurafshon business');
INSERT INTO lib_publishings (id, name) VALUES (159, 'Tafakkur qanotida');
INSERT INTO lib_publishings (id, name) VALUES (160, 'Ilm-Ziyo zakovat');
INSERT INTO lib_publishings (id, name) VALUES (161, 'Fanlar akademiyasi');
INSERT INTO lib_publishings (id, name) VALUES (162, 'Hilol-Nashr');
INSERT INTO lib_publishings (id, name) VALUES (163, 'Tafakkur tomchilari');
INSERT INTO lib_publishings (id, name) VALUES (164, 'Uzbekiston xalqlar islom akademiyasi');
INSERT INTO lib_publishings (id, name) VALUES (165, 'Buxoro nashr');
INSERT INTO lib_publishings (id, name) VALUES (166, 'Jizzax');
INSERT INTO lib_publishings (id, name) VALUES (167, 'Xalq merosi');
INSERT INTO lib_publishings (id, name) VALUES (168, 'Yuksalish');
INSERT INTO lib_publishings (id, name) VALUES (169, 'Terra Print  Klaster LLC');
INSERT INTO lib_publishings (id, name) VALUES (170, 'Qarshi');
INSERT INTO lib_publishings (id, name) VALUES (171, 'Fargona ');
INSERT INTO lib_publishings (id, name) VALUES (172, 'Axborot resurs');
INSERT INTO lib_publishings (id, name) VALUES (173, 'Zabarjad media');
INSERT INTO lib_publishings (id, name) VALUES (174, 'Tohir Malik');
INSERT INTO lib_publishings (id, name) VALUES (175, 'yangi yol Poligraph service');
INSERT INTO lib_publishings (id, name) VALUES (176, 'Iqtisodiyot dunyosi');
INSERT INTO lib_publishings (id, name) VALUES (177, 'Donish chirog''i');
INSERT INTO lib_publishings (id, name) VALUES (178, 'Ziyo');
INSERT INTO lib_publishings (id, name) VALUES (179, 'Sadriddin Salim Buxoriy');
INSERT INTO lib_publishings (id, name) VALUES (180, 'Nashriyot-matbaa');
INSERT INTO lib_publishings (id, name) VALUES (181, 'Maorif');
INSERT INTO lib_publishings (id, name) VALUES (182, 'Silk Road Media');
INSERT INTO lib_publishings (id, name) VALUES (183, 'BIF MSH');
INSERT INTO lib_publishings (id, name) VALUES (184, 'BDU');
INSERT INTO lib_publishings (id, name) VALUES (185, '???µ???° ?‘?°N?N‹??');
INSERT INTO lib_publishings (id, name) VALUES (186, 'Mega Basim');
INSERT INTO lib_publishings (id, name) VALUES (187, 'Renessanspress ');
INSERT INTO lib_publishings (id, name) VALUES (188, 'Mashhur - press');
INSERT INTO lib_publishings (id, name) VALUES (189, 'O''zkitob savdo nashriyoti');
INSERT INTO lib_publishings (id, name) VALUES (190, 'Uzkitob savdo nashriyoti');
INSERT INTO lib_publishings (id, name) VALUES (191, 'Zamin Nashr');
INSERT INTO lib_publishings (id, name) VALUES (192, 'Ozbekiston');
INSERT INTO lib_publishings (id, name) VALUES (193, 'O''zbekiston');
INSERT INTO lib_publishings (id, name) VALUES (194, 'Sahhof');
INSERT INTO lib_publishings (id, name) VALUES (195, 'Nodirabegim');
INSERT INTO lib_publishings (id, name) VALUES (196, 'Akademiya');
INSERT INTO lib_publishings (id, name) VALUES (197, ' Info Capital Group');
INSERT INTO lib_publishings (id, name) VALUES (198, 'Info Capital Group');
INSERT INTO lib_publishings (id, name) VALUES (199, 'Yuridik adabiyotlar publish');
INSERT INTO lib_publishings (id, name) VALUES (200, 'Nurafshon');
INSERT INTO lib_publishings (id, name) VALUES (201, 'Zukko kitobxon');
INSERT INTO lib_publishings (id, name) VALUES (202, 'Read Book');
INSERT INTO lib_publishings (id, name) VALUES (203, 'Yurist-media');
INSERT INTO lib_publishings (id, name) VALUES (204, 'Davr Nashriyoti');
INSERT INTO lib_publishings (id, name) VALUES (205, 'Moskva Eksmo');
INSERT INTO lib_publishings (id, name) VALUES (206, 'Moskva Simbat');
INSERT INTO lib_publishings (id, name) VALUES (207, 'Moskva UMka');
INSERT INTO lib_publishings (id, name) VALUES (208, 'Moskva Eksmodestvo');
INSERT INTO lib_publishings (id, name) VALUES (209, '?Z?·?????  ???°???»?°N‚ ?ZO›N??? ???µ???°???????????°');
INSERT INTO lib_publishings (id, name) VALUES (210, 'O''rta va oliy makab');
INSERT INTO lib_publishings (id, name) VALUES (211, 'Urta va oliy maktab');
INSERT INTO lib_publishings (id, name) VALUES (212, 'Ibn Sino nomidagi nashriyot matbaa birlashmasi');
INSERT INTO lib_publishings (id, name) VALUES (213, 'Uzbek  Sovet Ensiklopediyasi Bosh redaksiyasi');
INSERT INTO lib_publishings (id, name) VALUES (214, 'Medisina');
INSERT INTO lib_publishings (id, name) VALUES (215, '???°N????°');
INSERT INTO lib_publishings (id, name) VALUES (216, 'Nauka');
INSERT INTO lib_publishings (id, name) VALUES (217, 'Mir');
INSERT INTO lib_publishings (id, name) VALUES (218, 'Prosveshenie');
INSERT INTO lib_publishings (id, name) VALUES (219, 'Pedagogika');
INSERT INTO lib_publishings (id, name) VALUES (220, 'Rostovskiy Universitet');
INSERT INTO lib_publishings (id, name) VALUES (221, 'ITA-Press');
INSERT INTO lib_publishings (id, name) VALUES (222, 'Alokachi');
INSERT INTO lib_publishings (id, name) VALUES (223, 'Gosudarstvennoe izdatelstvo texniko-teoreticheskoy literaturi');
INSERT INTO lib_publishings (id, name) VALUES (224, 'Znanie');
INSERT INTO lib_publishings (id, name) VALUES (225, 'Narodnay asveta');
INSERT INTO lib_publishings (id, name) VALUES (226, 'Mashinostroyenie');
INSERT INTO lib_publishings (id, name) VALUES (227, 'Kiev');
INSERT INTO lib_publishings (id, name) VALUES (228, '?’N‹N?N??°N? N??????»?°');
INSERT INTO lib_publishings (id, name) VALUES (229, 'Statistika');
INSERT INTO lib_publishings (id, name) VALUES (230, 'Novosibirsk');
INSERT INTO lib_publishings (id, name) VALUES (231, 'Leningrad');
INSERT INTO lib_publishings (id, name) VALUES (232, 'Izdatelstvo Moskovskogo Universiteta');
INSERT INTO lib_publishings (id, name) VALUES (233, 'Gosudarstvennoe izdatelstvo fiziko-matematicheskoy literaturi');
INSERT INTO lib_publishings (id, name) VALUES (234, 'Gosudarstvennoe izdatelstvo inostrannoy literaturi');
INSERT INTO lib_publishings (id, name) VALUES (235, 'Gosudarstvennoe statisticheskoe izdatelstvo');
INSERT INTO lib_publishings (id, name) VALUES (236, 'Krasnodar');
INSERT INTO lib_publishings (id, name) VALUES (237, 'Mesniereba');
INSERT INTO lib_publishings (id, name) VALUES (238, 'Sverdlovsk');
INSERT INTO lib_publishings (id, name) VALUES (239, 'Minsk');
INSERT INTO lib_publishings (id, name) VALUES (240, 'Tver');
INSERT INTO lib_publishings (id, name) VALUES (241, 'Saransk');
INSERT INTO lib_publishings (id, name) VALUES (242, 'Gorkiy');
INSERT INTO lib_publishings (id, name) VALUES (243, 'Alma-Ata');
INSERT INTO lib_publishings (id, name) VALUES (244, 'IHIT');
INSERT INTO lib_publishings (id, name) VALUES (245, 'Kuybishev');
INSERT INTO lib_publishings (id, name) VALUES (246, 'Nauka i texnika');
INSERT INTO lib_publishings (id, name) VALUES (247, 'Tech-Export Services Corridor ');
INSERT INTO lib_publishings (id, name) VALUES (248, 'Delo i servis');
INSERT INTO lib_publishings (id, name) VALUES (249, 'Saratov');
INSERT INTO lib_publishings (id, name) VALUES (250, 'Kishinev');
INSERT INTO lib_publishings (id, name) VALUES (251, 'Voronej');
INSERT INTO lib_publishings (id, name) VALUES (252, 'Energiay');
INSERT INTO lib_publishings (id, name) VALUES (253, 'Xarkov');
INSERT INTO lib_publishings (id, name) VALUES (254, 'Molodaya gvardiya');
INSERT INTO lib_publishings (id, name) VALUES (255, 'Elista');
INSERT INTO lib_publishings (id, name) VALUES (256, 'Istiqlol');
INSERT INTO lib_publishings (id, name) VALUES (257, 'o''zbekiston nyozuvchilar uyishmasi Adabiyot jamg''armasi nashriyoti');
INSERT INTO lib_publishings (id, name) VALUES (258, 'Adabiyot jamg`armasi nashriyoti');
INSERT INTO lib_publishings (id, name) VALUES (259, 'Amerika Qo''shma Shtatlarining axborot bo''limi');
INSERT INTO lib_publishings (id, name) VALUES (260, 'Toshkent Moliya Instituti');
INSERT INTO lib_publishings (id, name) VALUES (261, 'AQSH');
INSERT INTO lib_publishings (id, name) VALUES (262, 'OAJBNT');
INSERT INTO lib_publishings (id, name) VALUES (263, 'N??°N€??');
INSERT INTO lib_publishings (id, name) VALUES (264, 'Tibbiyot Nashrioti');
INSERT INTO lib_publishings (id, name) VALUES (265, 'Norma');
INSERT INTO lib_publishings (id, name) VALUES (266, 'Zarafshon nashr');
INSERT INTO lib_publishings (id, name) VALUES (267, 'Misil');
INSERT INTO lib_publishings (id, name) VALUES (268, 'Ekonomika');
INSERT INTO lib_publishings (id, name) VALUES (269, 'Finannsi');
INSERT INTO lib_publishings (id, name) VALUES (270, 'Respublika');
INSERT INTO lib_publishings (id, name) VALUES (271, 'quvasay');
INSERT INTO lib_publishings (id, name) VALUES (272, 'ACA');
INSERT INTO lib_publishings (id, name) VALUES (273, 'Poligrafresurs');
INSERT INTO lib_publishings (id, name) VALUES (274, '???·???°N‚?µ?»N?N?N‚???? ?·???°?????µ');
INSERT INTO lib_publishings (id, name) VALUES (275, 'Mir ekonomiki i mira');
INSERT INTO lib_publishings (id, name) VALUES (276, 'Agropromizdat');
INSERT INTO lib_publishings (id, name) VALUES (277, 'infra-M-Ngaeiu');
INSERT INTO lib_publishings (id, name) VALUES (278, 'Politizdat');
INSERT INTO lib_publishings (id, name) VALUES (279, 'piter');
INSERT INTO lib_publishings (id, name) VALUES (280, 'United Nations');
INSERT INTO lib_publishings (id, name) VALUES (281, 'Teis');
INSERT INTO lib_publishings (id, name) VALUES (282, 'Ekor');
INSERT INTO lib_publishings (id, name) VALUES (283, 'Nedra');
INSERT INTO lib_publishings (id, name) VALUES (284, 'Maskva progress');
INSERT INTO lib_publishings (id, name) VALUES (285, 'Naukova dumka');
INSERT INTO lib_publishings (id, name) VALUES (286, '??N?????N?N‚N€???µ?????µ');
INSERT INTO lib_publishings (id, name) VALUES (287, 'sudostroeniye');
INSERT INTO lib_publishings (id, name) VALUES (288, 'Ijod dunyosi');
INSERT INTO lib_publishings (id, name) VALUES (289, 'misli');
INSERT INTO lib_publishings (id, name) VALUES (290, 'Mejdunarodnie otnosheniya');
INSERT INTO lib_publishings (id, name) VALUES (291, 'Women');
INSERT INTO lib_publishings (id, name) VALUES (292, 'Ziyo-Rizograf');
INSERT INTO lib_publishings (id, name) VALUES (293, 'Yozuvchi');
INSERT INTO lib_publishings (id, name) VALUES (294, 'Faylasuflar milliy jamiyat nashriyoti');
INSERT INTO lib_publishings (id, name) VALUES (295, 'The Bhaktivedanta Book Trust');
INSERT INTO lib_publishings (id, name) VALUES (296, 'O''qituvchi');
INSERT INTO lib_publishings (id, name) VALUES (297, '???·?±?µ????N?N‚???? ?????  ???°???»?°N‚ ???°N?N€??N‘N‚??');
INSERT INTO lib_publishings (id, name) VALUES (298, 'Uzbekiston SSR davlat nashriyoti');
INSERT INTO lib_publishings (id, name) VALUES (299, 'Iqtisodiyot  va huquq dunyosi');
INSERT INTO lib_publishings (id, name) VALUES (300, 'Orta va oliy martab');
INSERT INTO lib_publishings (id, name) VALUES (301, 'Energiya');
INSERT INTO lib_publishings (id, name) VALUES (302, 'Sovetskoye radio');
INSERT INTO lib_publishings (id, name) VALUES (303, 'Lenizdat');
INSERT INTO lib_publishings (id, name) VALUES (304, 'Energoizdat');
INSERT INTO lib_publishings (id, name) VALUES (305, 'Legprombitizdat');
INSERT INTO lib_publishings (id, name) VALUES (306, 'N…??????N?');
INSERT INTO lib_publishings (id, name) VALUES (307, 'polimya');
INSERT INTO lib_publishings (id, name) VALUES (308, 'Transport');
INSERT INTO lib_publishings (id, name) VALUES (309, 'Dosaf');
INSERT INTO lib_publishings (id, name) VALUES (310, 'Abu ali ibn sino ');
INSERT INTO lib_publishings (id, name) VALUES (311, 'Rosvuzizdat');
INSERT INTO lib_publishings (id, name) VALUES (312, 'Elm');
INSERT INTO lib_publishings (id, name) VALUES (313, 'Yosh gvardiya');
INSERT INTO lib_publishings (id, name) VALUES (314, 'Minhoj');
INSERT INTO lib_publishings (id, name) VALUES (315, 'Ruskiy yazik');
INSERT INTO lib_publishings (id, name) VALUES (316, 'Progress');
INSERT INTO lib_publishings (id, name) VALUES (317, 'Irkutck');
INSERT INTO lib_publishings (id, name) VALUES (318, 'Ukraina');
INSERT INTO lib_publishings (id, name) VALUES (319, 'Akademi nauk');
INSERT INTO lib_publishings (id, name) VALUES (320, 'detskaya literatura');
INSERT INTO lib_publishings (id, name) VALUES (321, 'Atomizdat');
INSERT INTO lib_publishings (id, name) VALUES (322, 'Texniko-teoreticheckoy');
INSERT INTO lib_publishings (id, name) VALUES (323, 'Profizdat');
INSERT INTO lib_publishings (id, name) VALUES (324, 'Litniinti');
INSERT INTO lib_publishings (id, name) VALUES (325, '????????N?');
INSERT INTO lib_publishings (id, name) VALUES (326, 'Ximiya');
INSERT INTO lib_publishings (id, name) VALUES (327, 'Boku');
INSERT INTO lib_publishings (id, name) VALUES (328, '?z?????·');
INSERT INTO lib_publishings (id, name) VALUES (329, '??oskovskogo universiteta');
INSERT INTO lib_publishings (id, name) VALUES (330, 'MGU');
INSERT INTO lib_publishings (id, name) VALUES (331, 'roctov-na- donu');
INSERT INTO lib_publishings (id, name) VALUES (332, 'Ryazan');
INSERT INTO lib_publishings (id, name) VALUES (333, 'Ilim');
INSERT INTO lib_publishings (id, name) VALUES (334, 'Inostrannoy literaturi');
INSERT INTO lib_publishings (id, name) VALUES (335, 'cheboksari');
INSERT INTO lib_publishings (id, name) VALUES (336, 'vladimir');
INSERT INTO lib_publishings (id, name) VALUES (337, 'Quybishev');
INSERT INTO lib_publishings (id, name) VALUES (338, 'Zinatne');
INSERT INTO lib_publishings (id, name) VALUES (339, 'YOSHKAR-OLA');
INSERT INTO lib_publishings (id, name) VALUES (340, 'Nalchik');
INSERT INTO lib_publishings (id, name) VALUES (341, 'Girvath ');
INSERT INTO lib_publishings (id, name) VALUES (342, '?????????µN€N???N‚?µN‚');
INSERT INTO lib_publishings (id, name) VALUES (343, 'lelingradskogo universiteta');
INSERT INTO lib_publishings (id, name) VALUES (344, 'Gosudarstvennoye nauchno-texnicheskoye izdatelstvo ximicheskoye literaturi');
INSERT INTO lib_publishings (id, name) VALUES (345, 'Metallurgiya');
INSERT INTO lib_publishings (id, name) VALUES (346, 'Moskovskaya universiteta');
INSERT INTO lib_publishings (id, name) VALUES (347, 'Yaroslavl');
INSERT INTO lib_publishings (id, name) VALUES (348, '??N??????¶?µN?N‚???µ?????°N? ?»??N‚?µN€?°N‚N?N€?°');
INSERT INTO lib_publishings (id, name) VALUES (349, 'xudojestvennaya literatura');
INSERT INTO lib_publishings (id, name) VALUES (350, 'ayastan');
INSERT INTO lib_publishings (id, name) VALUES (351, 'Tadjikgosizdat');
INSERT INTO lib_publishings (id, name) VALUES (352, 'Pravda');
INSERT INTO lib_publishings (id, name) VALUES (353, 'Merani');
INSERT INTO lib_publishings (id, name) VALUES (354, 'Sovremennik');
INSERT INTO lib_publishings (id, name) VALUES (355, 'Fundamental bibiloteka');
INSERT INTO lib_publishings (id, name) VALUES (356, 'kzil uzbekistan');
INSERT INTO lib_publishings (id, name) VALUES (357, 'Mokslas');
INSERT INTO lib_publishings (id, name) VALUES (358, 'Knijnaya palata');
INSERT INTO lib_publishings (id, name) VALUES (359, 'Stalinabad');
INSERT INTO lib_publishings (id, name) VALUES (360, 'Sovetskaya Rossiya');
INSERT INTO lib_publishings (id, name) VALUES (361, 'Belarus');
INSERT INTO lib_publishings (id, name) VALUES (362, 'Yunona');
INSERT INTO lib_publishings (id, name) VALUES (363, 'Sovetskiy kompozitor');
INSERT INTO lib_publishings (id, name) VALUES (364, 'Dnipro');
INSERT INTO lib_publishings (id, name) VALUES (365, '???°N?N‚?°N†???°N? ?»??N‚?°N€?°N‚N?N€?°');
INSERT INTO lib_publishings (id, name) VALUES (366, 'Izvestiya');
INSERT INTO lib_publishings (id, name) VALUES (367, 'mastatskaya literatura');
INSERT INTO lib_publishings (id, name) VALUES (368, 'Ministerstva oboroni');
INSERT INTO lib_publishings (id, name) VALUES (369, 'Drujbi narodov');
INSERT INTO lib_publishings (id, name) VALUES (370, 'Baku Azernashr');
INSERT INTO lib_publishings (id, name) VALUES (371, 'Molodoy Kolxoznik');
INSERT INTO lib_publishings (id, name) VALUES (372, 'Bilim');
INSERT INTO lib_publishings (id, name) VALUES (373, 'Raduga');
INSERT INTO lib_publishings (id, name) VALUES (374, '?Y???»??N‚?µN… -?YN€?µN?N? ???°???? -?Y?µN‚?µN€?±N?N€??N??????? ?????»??N‚?µN…????N‡?µN??????? N????');
INSERT INTO lib_publishings (id, name) VALUES (375, '???±???»??N???');
INSERT INTO lib_publishings (id, name) VALUES (376, '?“N????°????N‚?°N€??N‹?? ???·???°N‚?µ?»N?N??????? N†?µ??N‚N€ ?’?›???”?z??');
INSERT INTO lib_publishings (id, name) VALUES (377, '                VLADOS');
INSERT INTO lib_publishings (id, name) VALUES (378, 'Vlados');
INSERT INTO lib_publishings (id, name) VALUES (379, 'O''zbek Dablat Jahon til univer');
INSERT INTO lib_publishings (id, name) VALUES (380, 'Jazuni');
INSERT INTO lib_publishings (id, name) VALUES (381, '?????s?? ?YN€?µN?N?');
INSERT INTO lib_publishings (id, name) VALUES (382, '??N?N‚?µNS?????? ');
INSERT INTO lib_publishings (id, name) VALUES (383, '??N?NSN‚?µ?????? ');
INSERT INTO lib_publishings (id, name) VALUES (384, '?¤?µ??????N?');
INSERT INTO lib_publishings (id, name) VALUES (385, 'Enpes ');
INSERT INTO lib_publishings (id, name) VALUES (386, '?????»?????°N? ?????°N€????N?');
INSERT INTO lib_publishings (id, name) VALUES (387, 'Maskva Xudojestvennae literatura');
INSERT INTO lib_publishings (id, name) VALUES (388, 'Mockva');
INSERT INTO lib_publishings (id, name) VALUES (389, 'Yulduzcha');
INSERT INTO lib_publishings (id, name) VALUES (390, 'Murmanskoe knijnoe izdatelstvo');
INSERT INTO lib_publishings (id, name) VALUES (391, 'Mockva Sovetskiy pisatel');
INSERT INTO lib_publishings (id, name) VALUES (392, 'Moskovskiy rabochiy');
INSERT INTO lib_publishings (id, name) VALUES (393, 'Kniga');
INSERT INTO lib_publishings (id, name) VALUES (394, 'Moskva Voennoe izdatelstova ');
INSERT INTO lib_publishings (id, name) VALUES (395, 'Nijne-Voljskoe');
INSERT INTO lib_publishings (id, name) VALUES (396, 'Alma-Ata Jazushi');
INSERT INTO lib_publishings (id, name) VALUES (397, 'Izdatelstvo literaturi i iskusstva imeni Gafura Gulyama');
INSERT INTO lib_publishings (id, name) VALUES (398, '?¤?°??');
INSERT INTO lib_publishings (id, name) VALUES (399, 'Mumbay');
INSERT INTO lib_publishings (id, name) VALUES (400, 'Qozon');
INSERT INTO lib_publishings (id, name) VALUES (401, 'Hindiston');
INSERT INTO lib_publishings (id, name) VALUES (402, 'Kogon');
INSERT INTO lib_publishings (id, name) VALUES (403, 'Pokiston');
INSERT INTO lib_publishings (id, name) VALUES (404, 'Turkiya');
INSERT INTO lib_publishings (id, name) VALUES (405, 'Saudiya Arabiston');
INSERT INTO lib_publishings (id, name) VALUES (406, 'Eron');
INSERT INTO lib_publishings (id, name) VALUES (407, 'Detskaya literatura Ministerstvo prosvesheniya RSFSR');
INSERT INTO lib_publishings (id, name) VALUES (408, 'Voennoe izdatelstvo Ministerstvo Oboroni');
INSERT INTO lib_publishings (id, name) VALUES (409, 'Iskusstvo');
INSERT INTO lib_publishings (id, name) VALUES (410, 'Vostochnoy literaturi');
INSERT INTO lib_publishings (id, name) VALUES (411, '????N??????° ??N??·?????°');
INSERT INTO lib_publishings (id, name) VALUES (412, 'Moskva Muzika');
INSERT INTO lib_publishings (id, name) VALUES (413, 'Izdatelstva " Pravda"');
INSERT INTO lib_publishings (id, name) VALUES (414, 'Sverdlovskoe knijnoe izdatelstvo');
INSERT INTO lib_publishings (id, name) VALUES (415, 'Voskresene');
INSERT INTO lib_publishings (id, name) VALUES (416, 'Ibn Sino');
INSERT INTO lib_publishings (id, name) VALUES (417, 'Akademii nauk SSSR');
INSERT INTO lib_publishings (id, name) VALUES (418, 'Panorama');
INSERT INTO lib_publishings (id, name) VALUES (419, 'Karakalpakstan');
INSERT INTO lib_publishings (id, name) VALUES (420, 'Toshkent xudojestvenay literatura');
INSERT INTO lib_publishings (id, name) VALUES (421, 'Olimp');
INSERT INTO lib_publishings (id, name) VALUES (422, 'Turkmenistan');
INSERT INTO lib_publishings (id, name) VALUES (423, 'Sharq nashriyoti ');
INSERT INTO lib_publishings (id, name) VALUES (424, '?z?“???—');
INSERT INTO lib_publishings (id, name) VALUES (425, 'Gospolitizdat');
INSERT INTO lib_publishings (id, name) VALUES (426, '????N????µ??N‚ SPLENDID');
INSERT INTO lib_publishings (id, name) VALUES (427, 'Toshkent Splendid');
INSERT INTO lib_publishings (id, name) VALUES (428, 'OGIZ');
INSERT INTO lib_publishings (id, name) VALUES (429, 'OGIZ-Cosekgiz');
INSERT INTO lib_publishings (id, name) VALUES (430, 'Al-hodiy xalqaro nashriyoti');
INSERT INTO lib_publishings (id, name) VALUES (431, 'Literaturi i iskusstva');
INSERT INTO lib_publishings (id, name) VALUES (432, 'Inastranay  literatura');
INSERT INTO lib_publishings (id, name) VALUES (433, 'Uch Ped Giz');
INSERT INTO lib_publishings (id, name) VALUES (434, 'Ivanova');
INSERT INTO lib_publishings (id, name) VALUES (435, 'Ashxabod');
INSERT INTO lib_publishings (id, name) VALUES (436, 'Vsya Moskva');
INSERT INTO lib_publishings (id, name) VALUES (437, 'Toshkent universiteti');
INSERT INTO lib_publishings (id, name) VALUES (438, 'Politicheskoy literatura');
INSERT INTO lib_publishings (id, name) VALUES (439, 'Buxoro Davlat Universiteti');
INSERT INTO lib_publishings (id, name) VALUES (440, 'Kazan');
INSERT INTO lib_publishings (id, name) VALUES (441, 'PRIOR');
INSERT INTO lib_publishings (id, name) VALUES (442, 'Ministerstva prosvisheniya RSFSR');
INSERT INTO lib_publishings (id, name) VALUES (443, 'Sovetskay  literatura');
INSERT INTO lib_publishings (id, name) VALUES (444, 'Pressa');
INSERT INTO lib_publishings (id, name) VALUES (445, 'Terra');
INSERT INTO lib_publishings (id, name) VALUES (446, 'Sofiy');
INSERT INTO lib_publishings (id, name) VALUES (447, 'Ulan-Ude');
INSERT INTO lib_publishings (id, name) VALUES (448, 'Maxachkala Daguchpegiz');
INSERT INTO lib_publishings (id, name) VALUES (449, '?•N€?µ???°??');
INSERT INTO lib_publishings (id, name) VALUES (450, 'Toshkent SHark');
INSERT INTO lib_publishings (id, name) VALUES (451, 'Osh');
INSERT INTO lib_publishings (id, name) VALUES (452, 'Adabiyot va san''at nashriyoti');
INSERT INTO lib_publishings (id, name) VALUES (453, 'Drujba  narodov');
INSERT INTO lib_publishings (id, name) VALUES (454, 'Moskva "Rus tili" nashriyoti');
INSERT INTO lib_publishings (id, name) VALUES (455, 'TAKT');
INSERT INTO lib_publishings (id, name) VALUES (456, 'Novosti');
INSERT INTO lib_publishings (id, name) VALUES (457, 'Radynskiy pismennik');
INSERT INTO lib_publishings (id, name) VALUES (458, 'DOSAAF SSSR');
INSERT INTO lib_publishings (id, name) VALUES (459, 'Ta`lim manbai');
INSERT INTO lib_publishings (id, name) VALUES (460, '??N???');
INSERT INTO lib_publishings (id, name) VALUES (461, '???°N????µ??N‚');
INSERT INTO lib_publishings (id, name) VALUES (462, '?’???»N???NZN?');
INSERT INTO lib_publishings (id, name) VALUES (463, 'Vilnyus');
INSERT INTO lib_publishings (id, name) VALUES (464, '<?¦?Y?????›?®>');
INSERT INTO lib_publishings (id, name) VALUES (465, 'SPIUL');
INSERT INTO lib_publishings (id, name) VALUES (466, 'O''AJBNT');
INSERT INTO lib_publishings (id, name) VALUES (467, 'Liesma');
INSERT INTO lib_publishings (id, name) VALUES (468, 'Xorazm ma`mun akademiyasi');
INSERT INTO lib_publishings (id, name) VALUES (469, 'Fizkultura i sport');
INSERT INTO lib_publishings (id, name) VALUES (470, 'Milano');
INSERT INTO lib_publishings (id, name) VALUES (471, 'Chirchik');
INSERT INTO lib_publishings (id, name) VALUES (472, 'Fan Ziyo');
INSERT INTO lib_publishings (id, name) VALUES (473, 'Samarqand Firuddin Esanzoda XC???§?s');
INSERT INTO lib_publishings (id, name) VALUES (474, 'Visshay shkola');
INSERT INTO lib_publishings (id, name) VALUES (475, 'Sovetskay  enseklopediy');
INSERT INTO lib_publishings (id, name) VALUES (476, 'Prosvesheniye');
INSERT INTO lib_publishings (id, name) VALUES (477, 'Morskoy transport');
INSERT INTO lib_publishings (id, name) VALUES (478, 'Misl');
INSERT INTO lib_publishings (id, name) VALUES (479, 'Logos');
INSERT INTO lib_publishings (id, name) VALUES (480, 'Sovetskaya nauka');
INSERT INTO lib_publishings (id, name) VALUES (481, 'Yozuvcyi');
INSERT INTO lib_publishings (id, name) VALUES (482, 'Kommunist');
INSERT INTO lib_publishings (id, name) VALUES (483, 'Shadrinsk');
INSERT INTO lib_publishings (id, name) VALUES (484, 'Glavnaya redaksiya vostochnoy literaturi');
INSERT INTO lib_publishings (id, name) VALUES (485, 'Sotsial''no-''konomicheskoy literatura');
INSERT INTO lib_publishings (id, name) VALUES (486, 'Sotsial''no-ekonomicheskoy literatura');
INSERT INTO lib_publishings (id, name) VALUES (487, 'Sotsialno-ekonomicheskaya literatura');
INSERT INTO lib_publishings (id, name) VALUES (488, 'Akademii nauk Azerbaydjanskoy SSR');
INSERT INTO lib_publishings (id, name) VALUES (489, 'Gosudarstvennoye sotsialno-ekonomicheskoye izdatelstvo');
INSERT INTO lib_publishings (id, name) VALUES (490, 'Kareliya');
INSERT INTO lib_publishings (id, name) VALUES (491, 'O`zbekiston SSR danlar akademiyasi nashriyoti');
INSERT INTO lib_publishings (id, name) VALUES (492, 'UzSSR fanlar akademiyasi');
INSERT INTO lib_publishings (id, name) VALUES (493, 'Miloserdie');
INSERT INTO lib_publishings (id, name) VALUES (494, 'Mektep');
INSERT INTO lib_publishings (id, name) VALUES (495, 'O`zSSR fanlar akademiyasi');
INSERT INTO lib_publishings (id, name) VALUES (496, 'Patriot');
INSERT INTO lib_publishings (id, name) VALUES (497, 'Smolenskoe');
INSERT INTO lib_publishings (id, name) VALUES (498, 'Akademii nauk Uzbekskoy SSR');
INSERT INTO lib_publishings (id, name) VALUES (499, 'Ensiklopediyai sovetii tochik');
INSERT INTO lib_publishings (id, name) VALUES (500, 'Mejdunarodnoy fond Ibn Sino');
INSERT INTO lib_publishings (id, name) VALUES (501, 'Qizil O`zbekiston');
INSERT INTO lib_publishings (id, name) VALUES (502, 'Qo`qon');
INSERT INTO lib_publishings (id, name) VALUES (503, 'Sovetskiy  xudojnik');
INSERT INTO lib_publishings (id, name) VALUES (504, 'Eesti raamat');
INSERT INTO lib_publishings (id, name) VALUES (505, 'Toshkent  mehnat');
INSERT INTO lib_publishings (id, name) VALUES (506, 'Toshkent "Muharrir"');
INSERT INTO lib_publishings (id, name) VALUES (507, 'Jazushi');
INSERT INTO lib_publishings (id, name) VALUES (508, 'Ma''naviyat');
INSERT INTO lib_publishings (id, name) VALUES (509, 'Imom Buxoriy xalqaro markazi');
INSERT INTO lib_publishings (id, name) VALUES (510, 'Soldatskoe slava');
INSERT INTO lib_publishings (id, name) VALUES (511, 'G`afur G`ulom nomidagi nashriyot-matbaa ijodiy uyi');
INSERT INTO lib_publishings (id, name) VALUES (512, 'O`zbekiston milliy ensiklopediyasi');
INSERT INTO lib_publishings (id, name) VALUES (513, 'Hilol nashr');
INSERT INTO lib_publishings (id, name) VALUES (514, 'Imom al-Buxoriy xalqaro jamg`armasi, Fridrix Erbet jamg`armasi');
INSERT INTO lib_publishings (id, name) VALUES (515, 'Yuridicheskaya literatura');
INSERT INTO lib_publishings (id, name) VALUES (516, 'Alfredo lopez');
INSERT INTO lib_publishings (id, name) VALUES (517, 'Kirgizistan');
INSERT INTO lib_publishings (id, name) VALUES (518, 'Navro`z');
INSERT INTO lib_publishings (id, name) VALUES (519, 'Toshkent  "Nur"');
INSERT INTO lib_publishings (id, name) VALUES (520, 'Peterburk');
INSERT INTO lib_publishings (id, name) VALUES (521, '???°N????µ??N‚-???°???°N€???°????');
INSERT INTO lib_publishings (id, name) VALUES (522, 'Tashkent-Samarkand');
INSERT INTO lib_publishings (id, name) VALUES (523, 'Ta''lim');
INSERT INTO lib_publishings (id, name) VALUES (524, 'ta`lim');
INSERT INTO lib_publishings (id, name) VALUES (525, 'Petrograd');
INSERT INTO lib_publishings (id, name) VALUES (526, 'East star media');
INSERT INTO lib_publishings (id, name) VALUES (527, 'Ewhan');
INSERT INTO lib_publishings (id, name) VALUES (528, 'Elmadad va Huquqiy axborot');
INSERT INTO lib_publishings (id, name) VALUES (529, 'A°letiAYim');
INSERT INTO lib_publishings (id, name) VALUES (530, 'IletA±AYA±m');
INSERT INTO lib_publishings (id, name) VALUES (531, 'IlA±tA±sA±m');
INSERT INTO lib_publishings (id, name) VALUES (532, 'Ilitisim');
INSERT INTO lib_publishings (id, name) VALUES (533, 'Iletisim');
INSERT INTO lib_publishings (id, name) VALUES (534, 'Falsa A°lA§e Milli EAYitim MA?dA?rlA?AYA?');
INSERT INTO lib_publishings (id, name) VALUES (535, 'A°nsan');
INSERT INTO lib_publishings (id, name) VALUES (536, 'Insan');
INSERT INTO lib_publishings (id, name) VALUES (537, 'BengA?');
INSERT INTO lib_publishings (id, name) VALUES (538, 'Bengu');
INSERT INTO lib_publishings (id, name) VALUES (539, 'Macmillan');
INSERT INTO lib_publishings (id, name) VALUES (540, 'Larousse');
INSERT INTO lib_publishings (id, name) VALUES (541, 'G`afur G`ulom nomidagi badiiy adabiyot nashriyoti');
INSERT INTO lib_publishings (id, name) VALUES (542, 'Muharrir nashriyoti');
INSERT INTO lib_publishings (id, name) VALUES (543, 'O`zbekiston Matbuot va axborot agentligi G`afur G`ulom nomidagi nashriyot-matbaa ijodiy uyi ');
INSERT INTO lib_publishings (id, name) VALUES (544, 'Uchpedgiz');
INSERT INTO lib_publishings (id, name) VALUES (545, 'Higer school publishing house');
INSERT INTO lib_publishings (id, name) VALUES (546, 'Vysheishaya Shkola Publishers');
INSERT INTO lib_publishings (id, name) VALUES (547, 'Denmark');
INSERT INTO lib_publishings (id, name) VALUES (548, 'Dushkin');
INSERT INTO lib_publishings (id, name) VALUES (549, 'Irwin');
INSERT INTO lib_publishings (id, name) VALUES (550, 'Buxara');
INSERT INTO lib_publishings (id, name) VALUES (551, 'Kamolot');
INSERT INTO lib_publishings (id, name) VALUES (552, 'Ekosan');
INSERT INTO lib_publishings (id, name) VALUES (553, 'Kichik akademiya');
INSERT INTO lib_publishings (id, name) VALUES (554, 'O`AJBNT');
INSERT INTO lib_publishings (id, name) VALUES (555, 'Petrozavodsk');
INSERT INTO lib_publishings (id, name) VALUES (556, 'Vologda');
INSERT INTO lib_publishings (id, name) VALUES (557, '?‘N?N…??N€??');
INSERT INTO lib_publishings (id, name) VALUES (558, 'Navoiy');
INSERT INTO lib_publishings (id, name) VALUES (559, '??????N€?????°');
INSERT INTO lib_publishings (id, name) VALUES (560, 'skorina');
INSERT INTO lib_publishings (id, name) VALUES (561, 'Buxorodon');
INSERT INTO lib_publishings (id, name) VALUES (562, '???°NSN€??N„?°N‚');
INSERT INTO lib_publishings (id, name) VALUES (563, 'Ma''rifat');
INSERT INTO lib_publishings (id, name) VALUES (564, 'Ma`rifat');
INSERT INTO lib_publishings (id, name) VALUES (565, 'Abdulla Qodiriy nomidagi xalq merosi nashriyoti');
INSERT INTO lib_publishings (id, name) VALUES (566, 'Tashkent');
INSERT INTO lib_publishings (id, name) VALUES (567, '??''qituvchi');
INSERT INTO lib_publishings (id, name) VALUES (568, '??qituvchi');
INSERT INTO lib_publishings (id, name) VALUES (569, '?????°?±??N‘N‚ N?N‡??N????»?°N€??');
INSERT INTO lib_publishings (id, name) VALUES (570, 'Buchara');
INSERT INTO lib_publishings (id, name) VALUES (571, 'Buxoro universiteti');
INSERT INTO lib_publishings (id, name) VALUES (572, 'bashkirskoe');
INSERT INTO lib_publishings (id, name) VALUES (573, 'planmeyyniy');
INSERT INTO lib_publishings (id, name) VALUES (574, 'polyus');
INSERT INTO lib_publishings (id, name) VALUES (575, 'Ma`naviyat');
INSERT INTO lib_publishings (id, name) VALUES (576, 'A.Qodiriy nomidagi XALQ MEROSI nashriyoti');
INSERT INTO lib_publishings (id, name) VALUES (577, 'Literaturnogo Fonda Soyuza Pisateley Respubliki Uzbekistan');
INSERT INTO lib_publishings (id, name) VALUES (578, 'Izdatelskogo-poligraficheskiy tvorcheskiy dom imeni Gafura Gulyama');
INSERT INTO lib_publishings (id, name) VALUES (579, 'ikpa');
INSERT INTO lib_publishings (id, name) VALUES (580, 'Knijniy dom');
INSERT INTO lib_publishings (id, name) VALUES (581, 'Riga');
INSERT INTO lib_publishings (id, name) VALUES (582, 'planeta');
INSERT INTO lib_publishings (id, name) VALUES (583, 'Mumtoz so`z');
INSERT INTO lib_publishings (id, name) VALUES (584, '?‘N?N…?°N€N??????? ????N?N????°N€N?N‚???µ????N‹?? N????????µN€N???N‚?µN‚');
INSERT INTO lib_publishings (id, name) VALUES (585, 'Buxarskiy gosudarstvenniy universitet');
INSERT INTO lib_publishings (id, name) VALUES (586, 'Chicago');
INSERT INTO lib_publishings (id, name) VALUES (587, 'Leipzig');
INSERT INTO lib_publishings (id, name) VALUES (588, 'Akademiai Kiado, Budapest');
INSERT INTO lib_publishings (id, name) VALUES (589, 'McGraww-Hill');
INSERT INTO lib_publishings (id, name) VALUES (590, 'ChGIK');
INSERT INTO lib_publishings (id, name) VALUES (591, 'Baku');
INSERT INTO lib_publishings (id, name) VALUES (592, 'TGEU');
INSERT INTO lib_publishings (id, name) VALUES (593, 'Chinor ENK');
INSERT INTO lib_publishings (id, name) VALUES (594, 'Postscript');
INSERT INTO lib_publishings (id, name) VALUES (595, 'Guilford');
INSERT INTO lib_publishings (id, name) VALUES (596, 'New Jersey');
INSERT INTO lib_publishings (id, name) VALUES (597, 'Laboratoriya Bazovix Znaniy');
INSERT INTO lib_publishings (id, name) VALUES (598, 'Omneo');
INSERT INTO lib_publishings (id, name) VALUES (599, 'John Wiley');
INSERT INTO lib_publishings (id, name) VALUES (600, 'Press');
INSERT INTO lib_publishings (id, name) VALUES (601, 'Altair');
INSERT INTO lib_publishings (id, name) VALUES (602, 'Sank-peterburskogo universiteta');
INSERT INTO lib_publishings (id, name) VALUES (603, 'Akvilon');
INSERT INTO lib_publishings (id, name) VALUES (604, 'Moskovskogo universiteta');
INSERT INTO lib_publishings (id, name) VALUES (605, 'Lomonosov Moscow State University');
INSERT INTO lib_publishings (id, name) VALUES (606, 'Izdatelstvo AST');
INSERT INTO lib_publishings (id, name) VALUES (607, 'EKSMO');
INSERT INTO lib_publishings (id, name) VALUES (608, 'Iran');
INSERT INTO lib_publishings (id, name) VALUES (609, 'Rostov-na-Donu');
INSERT INTO lib_publishings (id, name) VALUES (610, 'Yujniy federalniy universitet');
INSERT INTO lib_publishings (id, name) VALUES (611, 'Muzey Moskovskogo Kremlya');
INSERT INTO lib_publishings (id, name) VALUES (612, 'Jahon iqtisodiyoti va diplomatiya universiteti');
INSERT INTO lib_publishings (id, name) VALUES (613, 'UNDP');
INSERT INTO lib_publishings (id, name) VALUES (614, 'Aleteyya');
INSERT INTO lib_publishings (id, name) VALUES (615, 'Moscow');
INSERT INTO lib_publishings (id, name) VALUES (616, 'Technology cooperation');
INSERT INTO lib_publishings (id, name) VALUES (617, 'Toshkent Kamakak');
INSERT INTO lib_publishings (id, name) VALUES (618, 'Nonparel');
INSERT INTO lib_publishings (id, name) VALUES (619, 'Albaniya');
INSERT INTO lib_publishings (id, name) VALUES (620, 'Kray Ra');
INSERT INTO lib_publishings (id, name) VALUES (621, 'WCB');
INSERT INTO lib_publishings (id, name) VALUES (622, 'Mosby');
INSERT INTO lib_publishings (id, name) VALUES (623, 'Limited');
INSERT INTO lib_publishings (id, name) VALUES (624, 'Chikago');
INSERT INTO lib_publishings (id, name) VALUES (625, 'University Librarries');
INSERT INTO lib_publishings (id, name) VALUES (626, 'Brown');
INSERT INTO lib_publishings (id, name) VALUES (627, 'Times Mirror');
INSERT INTO lib_publishings (id, name) VALUES (628, 'America');
INSERT INTO lib_publishings (id, name) VALUES (629, 'New York');
INSERT INTO lib_publishings (id, name) VALUES (630, 'Sharg');
INSERT INTO lib_publishings (id, name) VALUES (631, 'CABI');
INSERT INTO lib_publishings (id, name) VALUES (632, 'Merril');
INSERT INTO lib_publishings (id, name) VALUES (633, 'Amerika qo`shma shtatlarining axborot bo`limi');
INSERT INTO lib_publishings (id, name) VALUES (634, 'DPG');
INSERT INTO lib_publishings (id, name) VALUES (635, 'Gill & Macmillan');
INSERT INTO lib_publishings (id, name) VALUES (636, 'Turon Nashr');
INSERT INTO lib_publishings (id, name) VALUES (637, 'Mahorat');
INSERT INTO lib_publishings (id, name) VALUES (638, 'Oregon');
INSERT INTO lib_publishings (id, name) VALUES (639, 'Springer');
INSERT INTO lib_publishings (id, name) VALUES (640, 'Kanada');
INSERT INTO lib_publishings (id, name) VALUES (641, 'EXTRA');
INSERT INTO lib_publishings (id, name) VALUES (642, 'Croatia');
INSERT INTO lib_publishings (id, name) VALUES (643, 'Longman');
INSERT INTO lib_publishings (id, name) VALUES (644, 'King Saud university');
INSERT INTO lib_publishings (id, name) VALUES (645, 'Guliston');
INSERT INTO lib_publishings (id, name) VALUES (646, 'Prisim');
INSERT INTO lib_publishings (id, name) VALUES (647, 'Prism');
INSERT INTO lib_publishings (id, name) VALUES (648, 'Peterson''s');
INSERT INTO lib_publishings (id, name) VALUES (649, 'Peterson`s');
INSERT INTO lib_publishings (id, name) VALUES (650, '??N????°N??°??');
INSERT INTO lib_publishings (id, name) VALUES (651, 'kuvasay');
INSERT INTO lib_publishings (id, name) VALUES (652, 'Cho''lpon');
INSERT INTO lib_publishings (id, name) VALUES (653, 'Bayrut');
INSERT INTO lib_publishings (id, name) VALUES (654, 'Katar');
INSERT INTO lib_publishings (id, name) VALUES (655, 'Addison-wesley');
INSERT INTO lib_publishings (id, name) VALUES (656, 'Random house');
INSERT INTO lib_publishings (id, name) VALUES (657, 'CEDAW');
INSERT INTO lib_publishings (id, name) VALUES (658, 'Peacock');
INSERT INTO lib_publishings (id, name) VALUES (659, 'Apprentis dauteuil');
INSERT INTO lib_publishings (id, name) VALUES (660, 'Ar -Riyod');
INSERT INTO lib_publishings (id, name) VALUES (661, 'Warszawa');
INSERT INTO lib_publishings (id, name) VALUES (662, 'Letudiant');
INSERT INTO lib_publishings (id, name) VALUES (663, 'Italia');
INSERT INTO lib_publishings (id, name) VALUES (664, 'Cambridge university library');
INSERT INTO lib_publishings (id, name) VALUES (665, 'Georgetown University');
INSERT INTO lib_publishings (id, name) VALUES (666, 'Nippon');
INSERT INTO lib_publishings (id, name) VALUES (667, 'nasaf');
INSERT INTO lib_publishings (id, name) VALUES (668, 'Damashk');
INSERT INTO lib_publishings (id, name) VALUES (669, 'Kohira');
INSERT INTO lib_publishings (id, name) VALUES (670, 'Soka Gakkai');
INSERT INTO lib_publishings (id, name) VALUES (671, 'Fast print');
INSERT INTO lib_publishings (id, name) VALUES (672, 'Misr');
INSERT INTO lib_publishings (id, name) VALUES (673, 'Sydney');
INSERT INTO lib_publishings (id, name) VALUES (674, 'Sweden');
INSERT INTO lib_publishings (id, name) VALUES (675, 'Bridge publications');
INSERT INTO lib_publishings (id, name) VALUES (676, 'Columbia university press');
INSERT INTO lib_publishings (id, name) VALUES (677, 'Palgrave');
INSERT INTO lib_publishings (id, name) VALUES (678, 'Japan');
INSERT INTO lib_publishings (id, name) VALUES (679, 'Makka');
INSERT INTO lib_publishings (id, name) VALUES (680, 'Stone Bridge Press');
INSERT INTO lib_publishings (id, name) VALUES (681, 'Weatherhill');
INSERT INTO lib_publishings (id, name) VALUES (682, 'Jidda');
INSERT INTO lib_publishings (id, name) VALUES (683, 'Cornell University Press');
INSERT INTO lib_publishings (id, name) VALUES (684, 'Penguin books');
INSERT INTO lib_publishings (id, name) VALUES (685, 'Oxford University Press');
INSERT INTO lib_publishings (id, name) VALUES (686, 'Kodansha international');
INSERT INTO lib_publishings (id, name) VALUES (687, 'University of California press');
INSERT INTO lib_publishings (id, name) VALUES (688, 'The University Press of Kentucky');
INSERT INTO lib_publishings (id, name) VALUES (689, 'The yomiuri shimbun');
INSERT INTO lib_publishings (id, name) VALUES (690, 'Princeton University Press');
INSERT INTO lib_publishings (id, name) VALUES (691, 'Quvayt');
INSERT INTO lib_publishings (id, name) VALUES (692, 'Davlatul-Xalij');
INSERT INTO lib_publishings (id, name) VALUES (693, 'Trans Pacific Press');
INSERT INTO lib_publishings (id, name) VALUES (694, 'Harvard University Press');
INSERT INTO lib_publishings (id, name) VALUES (695, 'Livan');
INSERT INTO lib_publishings (id, name) VALUES (696, 'Cambridge university Press');
INSERT INTO lib_publishings (id, name) VALUES (697, 'Pantheon books');
INSERT INTO lib_publishings (id, name) VALUES (698, 'Stanford University Press');
INSERT INTO lib_publishings (id, name) VALUES (699, 'Tunis');
INSERT INTO lib_publishings (id, name) VALUES (700, 'Brookings Institution Press');
INSERT INTO lib_publishings (id, name) VALUES (701, 'Clarendon Press');
INSERT INTO lib_publishings (id, name) VALUES (702, 'Yale University Press');
INSERT INTO lib_publishings (id, name) VALUES (703, 'Naval Institute Press');
INSERT INTO lib_publishings (id, name) VALUES (704, 'A touchstone book');
INSERT INTO lib_publishings (id, name) VALUES (705, 'Houghton mifflin company');
INSERT INTO lib_publishings (id, name) VALUES (706, 'Blackwell');
INSERT INTO lib_publishings (id, name) VALUES (707, 'International Library Foundation');
INSERT INTO lib_publishings (id, name) VALUES (708, 'Global oriental');
INSERT INTO lib_publishings (id, name) VALUES (709, 'University of Hawai''i Press');
INSERT INTO lib_publishings (id, name) VALUES (710, 'University of Hawai`i Press');
INSERT INTO lib_publishings (id, name) VALUES (711, 'Council on foreign relations press');
INSERT INTO lib_publishings (id, name) VALUES (712, 'Routledge');
INSERT INTO lib_publishings (id, name) VALUES (713, 'Japan library');
INSERT INTO lib_publishings (id, name) VALUES (714, 'The Nippon Foundation');
INSERT INTO lib_publishings (id, name) VALUES (715, 'Duke University Press');
INSERT INTO lib_publishings (id, name) VALUES (716, 'M.E. Sharpe');
INSERT INTO lib_publishings (id, name) VALUES (717, 'Fiction in contemporary Japan');
INSERT INTO lib_publishings (id, name) VALUES (718, 'Tuttle');
INSERT INTO lib_publishings (id, name) VALUES (719, 'Cheng & Tsui company');
INSERT INTO lib_publishings (id, name) VALUES (720, 'Columbia university');
INSERT INTO lib_publishings (id, name) VALUES (721, 'Vintage books');
INSERT INTO lib_publishings (id, name) VALUES (722, 'SBP');
INSERT INTO lib_publishings (id, name) VALUES (723, 'The University Michigan ');
INSERT INTO lib_publishings (id, name) VALUES (724, 'German Democtaric Republic');
INSERT INTO lib_publishings (id, name) VALUES (725, 'SCHUBERT-Verlag Leipzig');
INSERT INTO lib_publishings (id, name) VALUES (726, 'Langenscheidt');
INSERT INTO lib_publishings (id, name) VALUES (727, 'CLE');
INSERT INTO lib_publishings (id, name) VALUES (728, 'Hachette');
INSERT INTO lib_publishings (id, name) VALUES (729, 'Humboldt');
INSERT INTO lib_publishings (id, name) VALUES (730, '??N?NZ-?™??N€??');
INSERT INTO lib_publishings (id, name) VALUES (731, 'Uppsala University');
INSERT INTO lib_publishings (id, name) VALUES (732, 'Brown & Benchmark');
INSERT INTO lib_publishings (id, name) VALUES (733, 'Max Hueber Verlag');
INSERT INTO lib_publishings (id, name) VALUES (734, 'Wilhelm heyne verlag');
INSERT INTO lib_publishings (id, name) VALUES (735, 'Le passeur');
INSERT INTO lib_publishings (id, name) VALUES (736, 'Helvetia');
INSERT INTO lib_publishings (id, name) VALUES (737, 'Mitteldeutscher verlag');
INSERT INTO lib_publishings (id, name) VALUES (738, 'New Era Publications ApS');
INSERT INTO lib_publishings (id, name) VALUES (739, 'Carl Hanser Verlag');
INSERT INTO lib_publishings (id, name) VALUES (740, 'Veb bibliographisches institut leipzig');
INSERT INTO lib_publishings (id, name) VALUES (741, 'Der Alltag');
INSERT INTO lib_publishings (id, name) VALUES (742, 'Ceic');
INSERT INTO lib_publishings (id, name) VALUES (743, 'Documentation-information-presse');
INSERT INTO lib_publishings (id, name) VALUES (744, 'Ummon');
INSERT INTO lib_publishings (id, name) VALUES (745, 'Afgoniston');
INSERT INTO lib_publishings (id, name) VALUES (746, 'Tehron');
INSERT INTO lib_publishings (id, name) VALUES (747, 'Bogdod');
INSERT INTO lib_publishings (id, name) VALUES (748, 'IEtudiand');
INSERT INTO lib_publishings (id, name) VALUES (749, 'Nathan');
INSERT INTO lib_publishings (id, name) VALUES (750, 'Hotel & Tourism business school');
INSERT INTO lib_publishings (id, name) VALUES (751, 'Bernard Grasset');
INSERT INTO lib_publishings (id, name) VALUES (752, 'Editions de fallois');
INSERT INTO lib_publishings (id, name) VALUES (753, 'Pocket');
INSERT INTO lib_publishings (id, name) VALUES (754, 'Fleuve noir');
INSERT INTO lib_publishings (id, name) VALUES (755, 'JC Lattes');
INSERT INTO lib_publishings (id, name) VALUES (756, 'Chastel');
INSERT INTO lib_publishings (id, name) VALUES (757, 'Les 3 Orangers');
INSERT INTO lib_publishings (id, name) VALUES (758, 'Mercvre de France');
INSERT INTO lib_publishings (id, name) VALUES (759, 'flammarion');
INSERT INTO lib_publishings (id, name) VALUES (760, 'Acted sud / Lemeac');
INSERT INTO lib_publishings (id, name) VALUES (761, 'Gallimard');
INSERT INTO lib_publishings (id, name) VALUES (762, 'Belfond');
INSERT INTO lib_publishings (id, name) VALUES (763, 'Robert laffont');
INSERT INTO lib_publishings (id, name) VALUES (764, 'Albin Michel');
INSERT INTO lib_publishings (id, name) VALUES (765, 'Gazi University');
INSERT INTO lib_publishings (id, name) VALUES (766, 'Tempus');
INSERT INTO lib_publishings (id, name) VALUES (767, 'Unip');
INSERT INTO lib_publishings (id, name) VALUES (768, 'Human development report');
INSERT INTO lib_publishings (id, name) VALUES (769, 'Korea');
INSERT INTO lib_publishings (id, name) VALUES (770, 'LTI Korea');
INSERT INTO lib_publishings (id, name) VALUES (771, 'IAUP');
INSERT INTO lib_publishings (id, name) VALUES (772, 'France');
INSERT INTO lib_publishings (id, name) VALUES (773, 'Iyerusalim');
INSERT INTO lib_publishings (id, name) VALUES (774, 'Autrement');
INSERT INTO lib_publishings (id, name) VALUES (775, 'Indian Institute of Finance');
INSERT INTO lib_publishings (id, name) VALUES (776, 'European Communities');
INSERT INTO lib_publishings (id, name) VALUES (777, 'Daad');
INSERT INTO lib_publishings (id, name) VALUES (778, 'SRK');
INSERT INTO lib_publishings (id, name) VALUES (779, 'The University of Nottingham');
INSERT INTO lib_publishings (id, name) VALUES (780, 'European Commission');
INSERT INTO lib_publishings (id, name) VALUES (781, 'Ilmiy-axborot nashri');
INSERT INTO lib_publishings (id, name) VALUES (782, 'Izrailskiy informatsionniy sentr');
INSERT INTO lib_publishings (id, name) VALUES (783, 'Verlag russkij jazyk');
INSERT INTO lib_publishings (id, name) VALUES (784, 'Madrid');
INSERT INTO lib_publishings (id, name) VALUES (785, 'Universidad de Alcala de Henares');
INSERT INTO lib_publishings (id, name) VALUES (786, 'Academia');
INSERT INTO lib_publishings (id, name) VALUES (787, 'Imom Buxoriy respublika ilmiy-ma''rifiy markazi');
INSERT INTO lib_publishings (id, name) VALUES (788, 'Imom Buxoriy respublika ilmiy-ma`rifiy markazi');
INSERT INTO lib_publishings (id, name) VALUES (789, 'Russkiy yazik');
INSERT INTO lib_publishings (id, name) VALUES (790, 'O`zbek Sovet ensiklopediyasi Bosh redaksiyasi');
INSERT INTO lib_publishings (id, name) VALUES (791, 'INFRA-M - NORMA');
INSERT INTO lib_publishings (id, name) VALUES (792, 'Vostochnaya literatura  ');
INSERT INTO lib_publishings (id, name) VALUES (793, 'Sankpeterburg');
INSERT INTO lib_publishings (id, name) VALUES (794, 'Suriya');
INSERT INTO lib_publishings (id, name) VALUES (795, 'Norma-INFRA - M');
INSERT INTO lib_publishings (id, name) VALUES (796, 'Ilmii ensiklopediyai sovetii tochik');
INSERT INTO lib_publishings (id, name) VALUES (797, 'Edizioni guerra - perugia');
INSERT INTO lib_publishings (id, name) VALUES (798, 'Carocci');
INSERT INTO lib_publishings (id, name) VALUES (799, 'Bonacci');
INSERT INTO lib_publishings (id, name) VALUES (800, 'Istituto geografico de Agostini');
INSERT INTO lib_publishings (id, name) VALUES (801, 'Universita degli studi di trento');
INSERT INTO lib_publishings (id, name) VALUES (802, 'Il Mulino');
INSERT INTO lib_publishings (id, name) VALUES (803, 'Vita Italiana');
INSERT INTO lib_publishings (id, name) VALUES (804, 'Odeon');
INSERT INTO lib_publishings (id, name) VALUES (805, 'Le Monnier');
INSERT INTO lib_publishings (id, name) VALUES (806, 'Cendali editori in Firenze');
INSERT INTO lib_publishings (id, name) VALUES (807, 'Guerra - Perugia');
INSERT INTO lib_publishings (id, name) VALUES (808, 'Ministero degli Affari Esteri');
INSERT INTO lib_publishings (id, name) VALUES (809, 'Diabasis');
INSERT INTO lib_publishings (id, name) VALUES (810, 'Guerra');
INSERT INTO lib_publishings (id, name) VALUES (811, 'Dilit');
INSERT INTO lib_publishings (id, name) VALUES (812, 'Mursia');
INSERT INTO lib_publishings (id, name) VALUES (813, 'Einaudi');
INSERT INTO lib_publishings (id, name) VALUES (814, 'Oscar Mondadori');
INSERT INTO lib_publishings (id, name) VALUES (815, 'Garzanti');
INSERT INTO lib_publishings (id, name) VALUES (816, 'Feltrinelli');
INSERT INTO lib_publishings (id, name) VALUES (817, 'Zanichelli');
INSERT INTO lib_publishings (id, name) VALUES (818, 'Liviya');
INSERT INTO lib_publishings (id, name) VALUES (819, 'Jazoir');
INSERT INTO lib_publishings (id, name) VALUES (820, 'Mashhad');
INSERT INTO lib_publishings (id, name) VALUES (821, 'Farvardin');
INSERT INTO lib_publishings (id, name) VALUES (822, 'Bahor');
INSERT INTO lib_publishings (id, name) VALUES (823, 'Yosh avlod matbaa');
INSERT INTO lib_publishings (id, name) VALUES (824, 'MALIK  Print CO');
INSERT INTO lib_publishings (id, name) VALUES (825, 'LUGO');
INSERT INTO lib_publishings (id, name) VALUES (826, 'TEX PRO-SILVER');
INSERT INTO lib_publishings (id, name) VALUES (827, ' Toshkent  "ZEBO PRINT"');
INSERT INTO lib_publishings (id, name) VALUES (828, 'Ishonchli hamkor');
INSERT INTO lib_publishings (id, name) VALUES (829, 'Zebo Print');
INSERT INTO lib_publishings (id, name) VALUES (830, 'Sharqi ozod');
INSERT INTO lib_publishings (id, name) VALUES (831, 'Maorif va farxang');
INSERT INTO lib_publishings (id, name) VALUES (832, 'Istedod');
INSERT INTO lib_publishings (id, name) VALUES (833, 'UKM press');
INSERT INTO lib_publishings (id, name) VALUES (834, 'Bangi');
INSERT INTO lib_publishings (id, name) VALUES (835, 'Gombak');
INSERT INTO lib_publishings (id, name) VALUES (836, 'Malaysia');
INSERT INTO lib_publishings (id, name) VALUES (837, 'Muosir');
INSERT INTO lib_publishings (id, name) VALUES (838, 'Perm Forvard-C');
INSERT INTO lib_publishings (id, name) VALUES (839, 'Buxoro S.S.Buxoriy');
INSERT INTO lib_publishings (id, name) VALUES (840, 'Bangladesh');
INSERT INTO lib_publishings (id, name) VALUES (841, 'Ekaterinburg');
INSERT INTO lib_publishings (id, name) VALUES (842, 'Uralskiy gosudarstvenniy universitet');
INSERT INTO lib_publishings (id, name) VALUES (843, 'Editions universitaires europeennes');
INSERT INTO lib_publishings (id, name) VALUES (844, 'Lap Lambert Academic Publishing');
INSERT INTO lib_publishings (id, name) VALUES (845, 'Yoshlar matbuoti');
INSERT INTO lib_publishings (id, name) VALUES (846, 'Qaqnus media');
INSERT INTO lib_publishings (id, name) VALUES (847, 'Qaldirgoch nashriyoti');
INSERT INTO lib_publishings (id, name) VALUES (848, 'Global books');
INSERT INTO lib_publishings (id, name) VALUES (849, 'Yosh kuch');
INSERT INTO lib_publishings (id, name) VALUES (850, 'Future-Books');
INSERT INTO lib_publishings (id, name) VALUES (851, 'Book media nashr');
INSERT INTO lib_publishings (id, name) VALUES (852, 'Shodlik nashriyoti');
INSERT INTO lib_publishings (id, name) VALUES (853, 'PIR');
INSERT INTO lib_publishings (id, name) VALUES (854, '''''Sano- standart''''');
INSERT INTO lib_publishings (id, name) VALUES (855, 'Cho''lpon nomidagi nashriyot- matbaa ijodiy uyi');
INSERT INTO lib_publishings (id, name) VALUES (856, 'Cho''lpon nomidagi nashriyot-matbaa ijodiy uyi ');
INSERT INTO lib_publishings (id, name) VALUES (857, 'Bukhara Hamd Print');
INSERT INTO lib_publishings (id, name) VALUES (858, 'Kitobdornashr');
INSERT INTO lib_publishings (id, name) VALUES (859, '???°????????');
INSERT INTO lib_publishings (id, name) VALUES (860, 'Noshirlik yog''dusi');
INSERT INTO lib_publishings (id, name) VALUES (861, 'Penza');
INSERT INTO lib_publishings (id, name) VALUES (862, 'Arxangelsk');
INSERT INTO lib_publishings (id, name) VALUES (863, 'Kirov');
INSERT INTO lib_publishings (id, name) VALUES (864, 'Lipetsk');
INSERT INTO lib_publishings (id, name) VALUES (865, 'Fan va ta''lim');
INSERT INTO lib_publishings (id, name) VALUES (866, 'Germaniya');
INSERT INTO lib_publishings (id, name) VALUES (867, 'Platon Maximos');
INSERT INTO lib_publishings (id, name) VALUES (868, 'Xitoy');
INSERT INTO lib_publishings (id, name) VALUES (869, 'Portugaliya');
INSERT INTO lib_publishings (id, name) VALUES (870, 'Belgiya');
INSERT INTO lib_publishings (id, name) VALUES (871, 'Vetnam');
INSERT INTO lib_publishings (id, name) VALUES (872, 'Niderlandiya');
INSERT INTO lib_publishings (id, name) VALUES (873, 'New Holland Publishers');
INSERT INTO lib_publishings (id, name) VALUES (874, 'Sofiya.Bulgariya');
INSERT INTO lib_publishings (id, name) VALUES (875, 'Shveysariya');
INSERT INTO lib_publishings (id, name) VALUES (876, 'Roger Raval Events');
INSERT INTO lib_publishings (id, name) VALUES (877, 'Yangi zellandiya');
INSERT INTO lib_publishings (id, name) VALUES (878, 'Leiden university press');
INSERT INTO lib_publishings (id, name) VALUES (879, 'Taschen Gmbh');
INSERT INTO lib_publishings (id, name) VALUES (880, 'Struik');
INSERT INTO lib_publishings (id, name) VALUES (881, 'CasteloArt Publishing LTD');
INSERT INTO lib_publishings (id, name) VALUES (882, 'Singapur');
INSERT INTO lib_publishings (id, name) VALUES (883, 'Polsha');
INSERT INTO lib_publishings (id, name) VALUES (884, 'Shvetsiya');
INSERT INTO lib_publishings (id, name) VALUES (885, 'Gollandiya');
INSERT INTO lib_publishings (id, name) VALUES (886, 'Lyuksemburg');
INSERT INTO lib_publishings (id, name) VALUES (887, 'Yevropa');
INSERT INTO lib_publishings (id, name) VALUES (888, 'Finlandiya');
INSERT INTO lib_publishings (id, name) VALUES (889, 'Praga');
INSERT INTO lib_publishings (id, name) VALUES (890, 'Ruminiya');
INSERT INTO lib_publishings (id, name) VALUES (891, 'Beaux-Arts Magazine');
INSERT INTO lib_publishings (id, name) VALUES (892, 'Indoneziya');
INSERT INTO lib_publishings (id, name) VALUES (893, 'Sahitya Akademi');
INSERT INTO lib_publishings (id, name) VALUES (894, 'Holding Company Ivan Fiodorov');
INSERT INTO lib_publishings (id, name) VALUES (895, 'Editon Temmen');
INSERT INTO lib_publishings (id, name) VALUES (896, 'Age-Art');
INSERT INTO lib_publishings (id, name) VALUES (897, 'Nouvelle version actualisee');
INSERT INTO lib_publishings (id, name) VALUES (898, 'Bukharest');
INSERT INTO lib_publishings (id, name) VALUES (899, 'Litva');
INSERT INTO lib_publishings (id, name) VALUES (900, 'Belgrad');
INSERT INTO lib_publishings (id, name) VALUES (901, 'Noviy mir');
INSERT INTO lib_publishings (id, name) VALUES (902, 'Neografiya');
INSERT INTO lib_publishings (id, name) VALUES (903, 'Vengriya');
INSERT INTO lib_publishings (id, name) VALUES (904, 'Avstriya');
INSERT INTO lib_publishings (id, name) VALUES (905, 'Norvegiya');
INSERT INTO lib_publishings (id, name) VALUES (906, 'Bishkek');
INSERT INTO lib_publishings (id, name) VALUES (907, 'Perfect');
INSERT INTO lib_publishings (id, name) VALUES (908, 'Slovakiya');
INSERT INTO lib_publishings (id, name) VALUES (909, 'SYL Creaciones Graficas');
INSERT INTO lib_publishings (id, name) VALUES (910, 'T:BOOK TRADE');
INSERT INTO lib_publishings (id, name) VALUES (911, 'T:History and Page');
INSERT INTO lib_publishings (id, name) VALUES (912, 'T;Book Trade Ko');
INSERT INTO lib_publishings (id, name) VALUES (913, '?z????N?');
INSERT INTO lib_publishings (id, name) VALUES (914, 'Omsk');
INSERT INTO lib_publishings (id, name) VALUES (915, 'Ispaniya');
INSERT INTO lib_publishings (id, name) VALUES (916, 'Toshkent PRINT MEDIA MCHJ');
INSERT INTO lib_publishings (id, name) VALUES (917, 'Surxon nashr');
INSERT INTO lib_publishings (id, name) VALUES (918, 'Toshkent Kafolat print company');
INSERT INTO lib_publishings (id, name) VALUES (919, '???°????N‚-?Y?µN‚?µN€?±N?N€??');
INSERT INTO lib_publishings (id, name) VALUES (920, '????N??????° ?????»???? - ?YN€?µN?N?');
INSERT INTO lib_publishings (id, name) VALUES (921, 'Belorus');
INSERT INTO lib_publishings (id, name) VALUES (922, 'Orenburg');
INSERT INTO lib_publishings (id, name) VALUES (923, 'Moldova');
INSERT INTO lib_publishings (id, name) VALUES (924, 'GlobeEdit');
INSERT INTO lib_publishings (id, name) VALUES (925, 'Shaxrisabz');
INSERT INTO lib_publishings (id, name) VALUES (926, 'Stavropol');
INSERT INTO lib_publishings (id, name) VALUES (927, '?’?»?°????????N€ ?’?»?“??.');
INSERT INTO lib_publishings (id, name) VALUES (928, '???»N?N???????N???');
INSERT INTO lib_publishings (id, name) VALUES (929, 'Taganrog');
INSERT INTO lib_publishings (id, name) VALUES (930, 'Elektron kitoblar');
INSERT INTO lib_publishings (id, name) VALUES (931, 'Great Britain');
INSERT INTO lib_publishings (id, name) VALUES (932, 'Barselona');
INSERT INTO lib_publishings (id, name) VALUES (933, 'TDYU');
INSERT INTO lib_publishings (id, name) VALUES (934, 'Tollyatti');
INSERT INTO lib_publishings (id, name) VALUES (935, 'Пермь');
INSERT INTO lib_publishings (id, name) VALUES (936, 'Кемерово');
INSERT INTO lib_publishings (id, name) VALUES (937, 'Samara');
INSERT INTO lib_publishings (id, name) VALUES (938, 'Toshkent  Yashil yaproq');
INSERT INTO lib_publishings (id, name) VALUES (939, 'Toshkent Bookmany print');
INSERT INTO lib_publishings (id, name) VALUES (940, 'Toshkent Zabarjad media');
INSERT INTO lib_publishings (id, name) VALUES (941, 'DENOV');
INSERT INTO lib_publishings (id, name) VALUES (942, 'Buxoro Hamd print');
INSERT INTO lib_publishings (id, name) VALUES (943, 'Toshkent Muhammad poligraf');
INSERT INTO lib_publishings (id, name) VALUES (944, ' Buxara Ipak yo`li');
INSERT INTO lib_publishings (id, name) VALUES (945, 'Buxara Umid');
INSERT INTO lib_publishings (id, name) VALUES (946, 'Buxara Brilliant cargo');
INSERT INTO lib_publishings (id, name) VALUES (947, 'Nurli dunyo');
INSERT INTO lib_publishings (id, name) VALUES (948, 'Novateurpublication');
INSERT INTO lib_publishings (id, name) VALUES (949, 'Best-publish');
INSERT INTO lib_publishings (id, name) VALUES (950, 'Тошкет Complex Print');
INSERT INTO lib_publishings (id, name) VALUES (951, 'Тошкент Pages print');
INSERT INTO lib_publishings (id, name) VALUES (952, 'Toshkent Dimal');
INSERT INTO lib_publishings (id, name) VALUES (953, 'Iqtisodiyot');
