INSERT INTO lib_resource_types (id, name) VALUES (1, 'Kitob');
INSERT INTO lib_resource_types (id, name) VALUES (2, 'Jurnal');
INSERT INTO lib_resource_types (id, name) VALUES (3, 'Gazeta');
INSERT INTO lib_resource_types (id, name) VALUES (4, ' O''quv uslubiy-qo`llanma');
INSERT INTO lib_resource_types (id, name) VALUES (5, 'Lug`at');
INSERT INTO lib_resource_types (id, name) VALUES (6, 'Darslik');
INSERT INTO lib_resource_types (id, name) VALUES (7, 'O''quv qo`llanma');
INSERT INTO lib_resource_types (id, name) VALUES (8, 'Avtoreferat');
INSERT INTO lib_resource_types (id, name) VALUES (9, 'Maqolalar to''plami');
INSERT INTO lib_resource_types (id, name) VALUES (10, 'Uslubiy majmua');
INSERT INTO lib_resource_types (id, name) VALUES (11, 'Amaliy qo''llanma');
INSERT INTO lib_resource_types (id, name) VALUES (12, 'Dissertatsiya');
INSERT INTO lib_resource_types (id, name) VALUES (13, 'Risola');
INSERT INTO lib_resource_types (id, name) VALUES (14, 'Ilmiy-uslubiy qo''llanma');
INSERT INTO lib_resource_types (id, name) VALUES (15, 'Monografiya');
INSERT INTO lib_resource_types (id, name) VALUES (16, 'Konferentsiya materiallari');
INSERT INTO lib_resource_types (id, name) VALUES (17, 'Ilmiy risola');
INSERT INTO lib_resource_types (id, name) VALUES (18, 'Ilmiy to''plam');
INSERT INTO lib_resource_types (id, name) VALUES (19, 'Qo''llanma');
INSERT INTO lib_resource_types (id, name) VALUES (20, 'Ilmiy o''quv-qo''llanma');
INSERT INTO lib_resource_types (id, name) VALUES (21, 'Badiiy adabiyot');
INSERT INTO lib_resource_types (id, name) VALUES (22, 'Uslubiy qo''llanma');
INSERT INTO lib_resource_types (id, name) VALUES (23, 'Tezislar to''plami');
INSERT INTO lib_resource_types (id, name) VALUES (24, 'Ensiklopediya');
INSERT INTO lib_resource_types (id, name) VALUES (25, 'Uslubiy tavsiya');
INSERT INTO lib_resource_types (id, name) VALUES (26, 'To''plam');
INSERT INTO lib_resource_types (id, name) VALUES (27, 'O`quv-metodik majmua');
INSERT INTO lib_resource_types (id, name) VALUES (28, 'Magistrlik dissertatsiyasi');
INSERT INTO lib_resource_types (id, name) VALUES (29, 'Chet el adabiyoti');
INSERT INTO lib_resource_types (id, name) VALUES (30, 'Ilmiy qo''llanma');
INSERT INTO lib_resource_types (id, name) VALUES (31, 'Ilmiy -amaliy anjuman materiallari');
INSERT INTO lib_resource_types (id, name) VALUES (32, 'Ilmiy va ilmiy-uslubiy maqollalar to''plami');
INSERT INTO lib_resource_types (id, name) VALUES (33, 'Statistik to''plam');
INSERT INTO lib_resource_types (id, name) VALUES (34, 'O''quv-uslubiy majmua');
INSERT INTO lib_resource_types (id, name) VALUES (35, 'Ilm -Toshkent');
INSERT INTO lib_resource_types (id, name) VALUES (36, 'Ma''lumotlar to''plami');
INSERT INTO lib_resource_types (id, name) VALUES (37, 'Ma''ruza matni');
INSERT INTO lib_resource_types (id, name) VALUES (38, 'Materiallar to''plami');
INSERT INTO lib_resource_types (id, name) VALUES (39, 'Ilmiy-uslubiy jurnal');
INSERT INTO lib_resource_types (id, name) VALUES (40, 'Uslubiy ko''rsatma');
INSERT INTO lib_resource_types (id, name) VALUES (41, 'Statistik blyuten');
INSERT INTO lib_resource_types (id, name) VALUES (42, 'Disk');
INSERT INTO lib_resource_types (id, name) VALUES (43, 'Ilmiy-ommabop risola');
INSERT INTO lib_resource_types (id, name) VALUES (44, 'Ommabop tavsiyalar');
INSERT INTO lib_resource_types (id, name) VALUES (45, 'Axborotnoma');
INSERT INTO lib_resource_types (id, name) VALUES (46, 'Ilmiy-ommabop tatqiqot');
INSERT INTO lib_resource_types (id, name) VALUES (47, 'Ilmiy ishlar to`plami');
INSERT INTO lib_resource_types (id, name) VALUES (48, 'Oraliq natija');
INSERT INTO lib_resource_types (id, name) VALUES (49, 'Hikmatlar');
INSERT INTO lib_resource_types (id, name) VALUES (50, 'Hikoyalar');
INSERT INTO lib_resource_types (id, name) VALUES (51, 'Qissa va hikoyalar');
INSERT INTO lib_resource_types (id, name) VALUES (52, 'Tarixiy biografik-ocherk');
INSERT INTO lib_resource_types (id, name) VALUES (53, 'Tarixiy roman');
INSERT INTO lib_resource_types (id, name) VALUES (54, 'Ilmiy-ma''rifiy adabiyot');
INSERT INTO lib_resource_types (id, name) VALUES (55, 'Tarixiy-adabiy yodgorlik');
INSERT INTO lib_resource_types (id, name) VALUES (56, 'Kitob-albom');
INSERT INTO lib_resource_types (id, name) VALUES (57, 'Ma`naviy - ma`rifiy meros');
INSERT INTO lib_resource_types (id, name) VALUES (58, 'matn');
INSERT INTO lib_resource_types (id, name) VALUES (59, 'Ilmiy-metodik ishlanma');
INSERT INTO lib_resource_types (id, name) VALUES (60, 'Ilmiy-uslubiy risola');
INSERT INTO lib_resource_types (id, name) VALUES (61, 'Asar');
INSERT INTO lib_resource_types (id, name) VALUES (62, 'Qo''lyoama');
INSERT INTO lib_resource_types (id, name) VALUES (63, 'Toshbosma');
INSERT INTO lib_resource_types (id, name) VALUES (64, 'Qo''lyozma');
INSERT INTO lib_resource_types (id, name) VALUES (65, 'Roman');
INSERT INTO lib_resource_types (id, name) VALUES (66, 'Komediya');
INSERT INTO lib_resource_types (id, name) VALUES (67, 'Povesti');
INSERT INTO lib_resource_types (id, name) VALUES (68, 'Stixi');
INSERT INTO lib_resource_types (id, name) VALUES (69, '? ?°N?N????°?·N‹');
INSERT INTO lib_resource_types (id, name) VALUES (70, 'Poema');
INSERT INTO lib_resource_types (id, name) VALUES (71, 'Statya');
INSERT INTO lib_resource_types (id, name) VALUES (72, 'Ocherk');
INSERT INTO lib_resource_types (id, name) VALUES (73, 'Povesti i rasskazi');
INSERT INTO lib_resource_types (id, name) VALUES (74, 'Rasskazi');
INSERT INTO lib_resource_types (id, name) VALUES (75, 'Ibn Sino');
INSERT INTO lib_resource_types (id, name) VALUES (76, 'N€?????°??');
INSERT INTO lib_resource_types (id, name) VALUES (77, 'P''esa');
INSERT INTO lib_resource_types (id, name) VALUES (78, 'Sobraniye i sochineniye');
INSERT INTO lib_resource_types (id, name) VALUES (79, 'Tragediya');
INSERT INTO lib_resource_types (id, name) VALUES (80, 'Skazki');
INSERT INTO lib_resource_types (id, name) VALUES (81, 'Avtobiografiya');
INSERT INTO lib_resource_types (id, name) VALUES (82, 'Trilogiya');
INSERT INTO lib_resource_types (id, name) VALUES (83, 'Novella');
INSERT INTO lib_resource_types (id, name) VALUES (84, 'Fantastika');
INSERT INTO lib_resource_types (id, name) VALUES (85, 'Proza');
INSERT INTO lib_resource_types (id, name) VALUES (86, 'O''quv-metodik qo''llanma');
INSERT INTO lib_resource_types (id, name) VALUES (87, 'Hajviya');
INSERT INTO lib_resource_types (id, name) VALUES (88, 'Doston');
INSERT INTO lib_resource_types (id, name) VALUES (89, 'She''rlar');
INSERT INTO lib_resource_types (id, name) VALUES (90, 'Drama');
INSERT INTO lib_resource_types (id, name) VALUES (91, 'Spravochnik');
INSERT INTO lib_resource_types (id, name) VALUES (92, 'Hujjatlar va materiallar to`plami');
INSERT INTO lib_resource_types (id, name) VALUES (93, 'Byulleten');
INSERT INTO lib_resource_types (id, name) VALUES (94, 'Otchyot ');
INSERT INTO lib_resource_types (id, name) VALUES (95, 'Usuliy qo`llanma');
INSERT INTO lib_resource_types (id, name) VALUES (96, 'Ilmiy amaliy qo`llanma');
INSERT INTO lib_resource_types (id, name) VALUES (97, 'Kodekslar');
INSERT INTO lib_resource_types (id, name) VALUES (98, 'Adabiy -badiiy nashr');
INSERT INTO lib_resource_types (id, name) VALUES (99, 'bestseller');
INSERT INTO lib_resource_types (id, name) VALUES (100, 'G''azallar');
INSERT INTO lib_resource_types (id, name) VALUES (101, 'Ilmiy-ommabop qo''llanma');
INSERT INTO lib_resource_types (id, name) VALUES (102, 'Universal qo''llanma');
INSERT INTO lib_resource_types (id, name) VALUES (103, '???°N?N‡???? - ?±??????N€?°N„??N‡?µN??????? N??±??N€??????');
INSERT INTO lib_resource_types (id, name) VALUES (104, 'Xalqaro ilmiy- amaliy amjuman');
INSERT INTO lib_resource_types (id, name) VALUES (105, 'Shavkat Mirziyoyev  kitoblari');
INSERT INTO lib_resource_types (id, name) VALUES (106, '?s?°N‚?°?»????');
INSERT INTO lib_resource_types (id, name) VALUES (107, 'Katalog');
INSERT INTO lib_resource_types (id, name) VALUES (108, '??N‡?µ?±?????µ  ????N????±???µ');
INSERT INTO lib_resource_types (id, name) VALUES (109, '?zN‚N‡?µN‚ ???? ??N€???µ??N‚N?');
INSERT INTO lib_resource_types (id, name) VALUES (110, 'Doklad');
INSERT INTO lib_resource_types (id, name) VALUES (111, 'Sbornik');
INSERT INTO lib_resource_types (id, name) VALUES (112, 'Qonunlar');
INSERT INTO lib_resource_types (id, name) VALUES (113, 'Savol- javob');
INSERT INTO lib_resource_types (id, name) VALUES (114, 'Qarorlar toplami');
INSERT INTO lib_resource_types (id, name) VALUES (115, '? ?????°??');
INSERT INTO lib_resource_types (id, name) VALUES (116, 'Brayl ');
INSERT INTO lib_resource_types (id, name) VALUES (117, 'Study guide');
INSERT INTO lib_resource_types (id, name) VALUES (118, 'Yangi Chirchiq  print');
INSERT INTO lib_resource_types (id, name) VALUES (119, 'Rasmiy nasr');
INSERT INTO lib_resource_types (id, name) VALUES (120, 'Konstitutsiya');
INSERT INTO lib_resource_types (id, name) VALUES (121, '??N‡?µ?±?????µ ????N????±???µ');
INSERT INTO lib_resource_types (id, name) VALUES (122, '?Y??N????±???µ');
INSERT INTO lib_resource_types (id, name) VALUES (123, 'Karta');
INSERT INTO lib_resource_types (id, name) VALUES (124, 'Atlas');
INSERT INTO lib_resource_types (id, name) VALUES (125, '?­?»?µ??N‚N€??????N‹?? N€?µN?N?N€N?');
INSERT INTO lib_resource_types (id, name) VALUES (126, 'Elektron resurs');
INSERT INTO lib_resource_types (id, name) VALUES (127, '???»N?N???????N???');
INSERT INTO lib_resource_types (id, name) VALUES (128, 'Tarixiy-ilmiy,ommabop publitsistik asar');
INSERT INTO lib_resource_types (id, name) VALUES (129, 'Bibliografik spravochnik');
INSERT INTO lib_resource_types (id, name) VALUES (130, 'Ilmiy va amaliy jurnal');
INSERT INTO lib_resource_types (id, name) VALUES (131, 'Tavsiyalar');
INSERT INTO lib_resource_types (id, name) VALUES (132, 'Биографический очерк');
INSERT INTO lib_resource_types (id, name) VALUES (133, 'Biograficheskiy ocherk');
INSERT INTO lib_resource_types (id, name) VALUES (134, 'Saylanma');
